// loop has 3 type 
// 1. for 
// 2. while 
// 3. do while 


#include <iostream>
using namespace std;





// int main(){
//     int count = 1;
//     while (count<=5){
//         cout<< count << endl;
//         count++;
//     }
//     return 0;
// }


// for loop 
// int main(){
//     int count= 12;
//     for (int i = 0; i < count; i++)
//     {
//         cout<< i << endl;
//     }
    

// }

// for loop syntex
// for (initialisation; condition;update)
// {
//     /* code */
// }



// int main(){
//     int n;
//     int i= 0, sum=0;
//     cout<<"enter a number: ";
//     cin>> n;
//     while (n>=i)
//     {
//         sum=sum+i;
//         i++;
//     }
//     cout << "sum is :" << sum;
//     return 0;
    
// }


//  odd number sum calcolator!

// int main(){
//     int n;
//     cout<<"Enter A Number: ";
//     cin>>n;
//     int sum=0;
//     while (n>=0)
//     {
//         if (n%2==1)
//         {
//           sum=sum+n;  
//         }
//         n--;
//     }
    
//     cout<<"Your odd number sum is :"<<sum;
//     return 0;
// }

// int main(){
//     int n;
//     cout<<"Enter A Number: ";
//     cin>>n;
//     int sum=0;
//     for (int i=1; i<=n; i++)
//     {
//        if (i%2==1)
//        {
//         sum = sum+i;
//        }
       
//     }
    
    
//     cout<<"Your odd number sum is :"<<sum;
//     return 0;
// }